version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "719905538647"
    AWS_REGION: "ap-southeast-2"
    LAYER_NAME: "common-utils-layer"
    USER_LAMBDA_NAME: "user-service"
    ORDER_LAMBDA_NAME: "order-service"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing layer dependencies..."
      - cd layers/common_layer/python
      - pip install -r requirements.txt -t .
      - cd ../../../

  build:
    commands:
      - echo "Packaging Lambda Layer..."
      - cd layers/common_layer
      - zip -r ../../common-layer.zip python
      - cd ../..

      - echo "Packaging User Lambda..."
      - cd lamdas/user_service
      - zip -r ../../user-service.zip .
      - cd ../..

      - echo "Packaging Order Lambda..."
      - cd lamdas/order_service
      - zip -r ../../order-service.zip .
      - cd ../..

  post_build:
    commands:
      - echo "Publishing new Layer Version..."
      - LAYER_VERSION=$(aws lambda publish-layer-version --layer-name $LAYER_NAME --zip-file fileb://common-layer.zip --query Version --output text)
      - echo "Published Layer Version: $LAYER_VERSION"

      - echo "Updating User Lambda Code..."
      - aws lambda update-function-code --function-name $USER_LAMBDA_NAME --zip-file fileb://user-service.zip
      - aws lambda wait function-updated --function-name $USER_LAMBDA_NAME

      - echo "Updating Order Lambda Code..."
      - aws lambda update-function-code --function-name $ORDER_LAMBDA_NAME --zip-file fileb://order-service.zip
      - aws lambda wait function-updated --function-name $ORDER_LAMBDA_NAME

      - echo "Attaching latest Layer to User Lambda..."
      - aws lambda update-function-configuration --function-name $USER_LAMBDA_NAME --layers arn:aws:lambda:$AWS_REGION:$AWS_ACCOUNT_ID:layer:$LAYER_NAME:$LAYER_VERSION
      - aws lambda wait function-updated --function-name $USER_LAMBDA_NAME

      - echo "Attaching latest Layer to Order Lambda..."
      - aws lambda update-function-configuration --function-name $ORDER_LAMBDA_NAME --layers arn:aws:lambda:$AWS_REGION:$AWS_ACCOUNT_ID:layer:$LAYER_NAME:$LAYER_VERSION
      - aws lambda wait function-updated --function-name $ORDER_LAMBDA_NAME

artifacts:
  files:
    - common-layer.zip
    - user-service.zip
    - order-service.zip